server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: 192.168.38.131
      port: 6379
      password: redis
mybatis:
  configuration:
    map-underscore-to-camel-case: true